Second attempt

diff --git a/.github/workflows/7. Initialize Blue Green Replication.yml b/.github/workflows/7. Initialize Blue Green Replication.yml
--- a/.github/workflows/7. Initialize Blue Green Replication.yml
+++ b/.github/workflows/7. Initialize Blue Green Replication.yml
@@ -19,8 +19,12 @@ on:
 jobs:
   Check-Inputs:
     runs-on: ubuntu-latest
+    outputs:
+      primary_server_color: ${{ steps.input-checker.outputs.PRIMARY_SERVER_COLOR }}
+      secondary_server_color: ${{ steps.input-checker.outputs.SECONDARY_SERVER_COLOR }}
     steps:
       - name: Check Inputs
+        id: input-checker
         run: | ## make sure hetzner_primary_server and hetzner_secondary_server are not the same, make sure one of them is Hetzner_blue and the other is Hetzner_green
           if [ "${{ github.event.inputs.hetzner_primary_server }}" == "${{ github.event.inputs.hetzner_secondary_server }}" ]; then
             echo "Error: hetzner_primary_server and hetzner_secondary_server cannot be the same."
@@ -35,11 +39,11 @@ jobs:
             exit 1
           fi
           if [ "${{ github.event.inputs.hetzner_primary_server }}" == "Hetzner_blue" ]; then
-            echo "PRIMARY_SERVER_COLOR=blue" >> $GITHUB_ENV
-            echo "SECONDARY_SERVER_COLOR=green" >> $GITHUB_ENV
+            echo "PRIMARY_SERVER_COLOR=blue" >> $GITHUB_OUTPUT
+            echo "SECONDARY_SERVER_COLOR=green" >> $GITHUB_OUTPUT
           else
-            echo "PRIMARY_SERVER_COLOR=green" >> $GITHUB_ENV
-            echo "SECONDARY_SERVER_COLOR=blue" >> $GITHUB_ENV
+            echo "PRIMARY_SERVER_COLOR=green" >> $GITHUB_OUTPUT
+            echo "SECONDARY_SERVER_COLOR=blue" >> $GITHUB_OUTPUT
           fi
 
   Check-Primary:
@@ -66,24 +70,26 @@ jobs:
 
       - name: Check colour and status match
         run: | ## check to see if ~/server_colour exists, if it does, check to see if the colour matches the server colour
-          if [ -f ~/server_colour ]; then
-            COLOUR=$(cat ~/server_colour)
-            if [ "$COLOUR" != "${{ env.PRIMARY_SERVER_COLOR }}" ]; then
-              echo "Error: server_colour does not match provided server colour."
-              exit 1
+          ssh staging '
+            if [ -f ~/server_colour ]; then
+              COLOUR=$(cat ~/server_colour)
+              if [ "$COLOUR" != "${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }}" ]; then
+                echo "Error: server_colour does not match provided server colour."
+                exit 1
+              fi
+            else
+              echo "${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }}" > ~/server_colour
             fi
-          else
-            echo "${{ env.PRIMARY_SERVER_COLOR }}" > ~/server_colour
-          fi
-          if [ -f ~/server_status ]; then
-            STATE=$(cat ~/server_status)
-            if [ "$STATE" != "primary" ]; then
-              echo "Error: server_status does not match provided server status."
-              exit 1
+            if [ -f ~/server_status ]; then
+              STATE=$(cat ~/server_status)
+              if [ "$STATE" != "primary" ]; then
+                echo "Error: server_status does not match provided server status."
+                exit 1
+              fi
+            else
+              echo "primary" > ~/server_status
             fi
-          else
-            echo "primary" > ~/server_status
-          fi
+          '
     
   Check-Secondary:
     needs: Check-Inputs
@@ -109,27 +115,29 @@ jobs:
 
       - name: Check colour and status match
         run: | ## check to see if ~/server_colour exists, if it does, check to see if the colour matches the server colour
-          if [ -f ~/server_colour ]; then
-            COLOUR=$(cat ~/server_colour)
-            if [ "$COLOUR" != "${{ env.SECONDARY_SERVER_COLOR }}" ]; then
-              echo "Error: server_colour does not match provided server colour."
-              exit 1
+          ssh staging '
+            if [ -f ~/server_colour ]; then
+              COLOUR=$(cat ~/server_colour)
+              if [ "$COLOUR" != "${{ needs.Check-Inputs.outputs.SECONDARY_SERVER_COLOR }}" ]; then
+                echo "Error: server_colour does not match provided server colour."
+                exit 1
+              fi
+            else
+              echo "${{ needs.Check-Inputs.outputs.SECONDARY_SERVER_COLOR }}" > ~/server_colour
             fi
-          else
-            echo "${{ env.SECONDARY_SERVER_COLOR }}" > ~/server_colour
-          fi
-          if [ -f ~/server_status ]; then
-            STATE=$(cat ~/server_status)
-            if [ "$STATE" != "secondary" ]; then
-              echo "Error: server_status does not match provided server status."
-              exit 1
+            if [ -f ~/server_status ]; then
+              STATE=$(cat ~/server_status)
+              if [ "$STATE" != "secondary" ]; then
+                echo "Error: server_status does not match provided server status."
+                exit 1
+              fi
+            else
+              echo "secondary" > ~/server_status
             fi
-          else
-            echo "secondary" > ~/server_status
-          fi
+          '
 
   Initialize-Primary:
-    needs: [Check-Primary, Check-Secondary]
+    needs: [Check-Inputs, Check-Primary, Check-Secondary]
     runs-on: ubuntu-latest
     environment: '${{ github.event.inputs.hetzner_primary_server }}'
     steps:
@@ -152,26 +160,28 @@ jobs:
 
       - name: Initialize Primary 
         run: |
-          PGPASSWORD=${{ secrets.MYSQL_PASS }} psql \
-            -U ${{ secrets.MYSQL_USER }} \
-            -d vermilion \
-            -h localhost <<'EOF'
-          DO $$
-          BEGIN
-            IF NOT EXISTS (
-              SELECT 1
-                FROM pg_publication
-               WHERE pubname = 'social_pub_from_${{ env.PRIMARY_SERVER_COLOR }}'
-            ) THEN
-              CREATE PUBLICATION social_pub_from_${{ env.PRIMARY_SERVER_COLOR }}
-                FOR TABLE social.test;
-            END IF;
-          END;
-          $$;
-          EOF
+          ssh staging '
+            PGPASSWORD=${{ secrets.MYSQL_PASS }} psql \
+              -U ${{ secrets.MYSQL_USER }} \
+              -d vermilion \
+              -h localhost <<'EOF'
+            DO $$
+            BEGIN
+              IF NOT EXISTS (
+                SELECT 1
+                  FROM pg_publication
+                WHERE pubname = 'social_pub_from_${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }}'
+              ) THEN
+                CREATE PUBLICATION social_pub_from_${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }}
+                  FOR TABLE social.test;
+              END IF;
+            END;
+            $$;
+            EOF
+          '
 
   Initialize-Secondary:
-    needs: Initialize-Primary
+    needs: [Check-Inputs, Initialize-Primary]
     runs-on: ubuntu-latest
     environment: '${{ github.event.inputs.hetzner_secondary_server }}'
     steps:
@@ -194,21 +204,23 @@ jobs:
 
       - name: Initialize Secondary 
         run: |
-          PGPASSWORD=${{ secrets.MYSQL_PASS }} psql \
-            -U ${{ secrets.MYSQL_USER }} \
-            -d vermilion \
-            -h localhost <<'EOF'
-          DO $$
-          BEGIN
-            IF NOT EXISTS (
-              SELECT 1
-                FROM pg_subscription
-               WHERE subname = 'social_sub_to_${{ env.PRIMARY_SERVER_COLOR }}'
-            ) THEN
-              CREATE SUBSCRIPTION social_sub_to_${{ env.PRIMARY_SERVER_COLOR }}
-                CONNECTION 'host=${{ vars.ALTERNATE_SERVER_HOST }} port=5432 user=${{ secrets.MYSQL_USER }} dbname=vermilion'
-                PUBLICATION social_pub_from_${{ env.PRIMARY_SERVER_COLOR }};
-            END IF;
-          END;
-          $$;
-          EOF
+          ssh staging '
+            PGPASSWORD=${{ secrets.MYSQL_PASS }} psql \
+              -U ${{ secrets.MYSQL_USER }} \
+              -d vermilion \
+              -h localhost <<'EOF'
+            DO $$
+            BEGIN
+              IF NOT EXISTS (
+                SELECT 1
+                  FROM pg_subscription
+                WHERE subname = 'social_sub_to_${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }}'
+              ) THEN
+                CREATE SUBSCRIPTION social_sub_to_${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }}
+                  CONNECTION 'host=${{ vars.ALTERNATE_SERVER_HOST }} port=5432 user=${{ secrets.MYSQL_USER }} dbname=vermilion'
+                  PUBLICATION social_pub_from_${{ needs.Check-Inputs.outputs.PRIMARY_SERVER_COLOR }};
+              END IF;
+            END;
+            $$;
+            EOF
+          '
